# Generated by Django 3.0.6 on 2020-05-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveysAdmin', '0002_auto_20200527_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='choice_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
